### ISSUE TITLE
Metadata section from Germline-StructuralV-nf

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/template-nf#3]
Are we planning to exclude the section [Metadata](https://github.com/Sydney-Informatics-Hub/Germline-StructuralV-nf/tree/main#metadata).
It seems to contain important information!

**Comment by georgiesamaha** [comment]
For that pipeline we used the [workflow documentation guidelines](https://github.com/AustralianBioCommons/doc_guidelines) to fill out the README. This public template is intended to be as flexible as possible and is focused on nextflow workflow repository structure, rather than documentation. Won't affix this to the template README, but will add a note in template-nf documentation recommending it.
